inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'app/controllers/line/**/*'

Rails:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
  Max: 85

Metrics/ClassLength:
  Max: 120

Layout/LineLength:
  Exclude:
    - 'config/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/HashAlignment:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'

Naming/AccessorMethodName:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Style/BlockDelimiters:
  Exclude:
    - 'spec/requests/**/*_spec.rb'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 5

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Rails/FilePath:
  Exclude:
    - 'config/**/*'
    - 'spec/rails_helper.rb'
